version: '3.8'

services:
  db:
    image: mysql:latest
    container_name: aura_docker_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: test123
      MYSQL_DATABASE: aura_docker
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - '3307:3306'

volumes:
  db_data:
